networks:
  lab_app_net:
    driver: bridge
services:
  webapp:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./backend/dockerfiles:/app/dockerfiles
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - lab_app_net

  frontend:
    build:
      context: ./frontend/labselector
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/labselector:/frontend
      - /frontend/node_modules
    command: npm run dev
    working_dir: /frontend
    networks:
      - lab_app_net

  exercise_container:
    image: kalilinux/kali-rolling
    container_name: exercise_container
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    command: ["/bin/bash"]
    networks:
      - lab_app_net