networks:
  lab_app_net:
    name: lab_app_net
    driver: bridge

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=replace-with-production-secret
    volumes:
      - ./dockerfiles:/app/dockerfiles
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab_app_net
    restart: always

  frontend:
    build:
      context: ./labselector
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://10.80.3.10:5001
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://10.80.3.10:5001
    command: "npm run start"
    networks:
      - lab_app_net
    restart: always

  exercise_container:
    image: kalilinux/kali-rolling
    container_name: exercise_container
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    command: ["/bin/bash"]
    networks:
      - lab_app_net
    restart: always