networks:
  lab_app_net:
    name: lab_app_net
    driver: bridge

services:
  webapp:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Permitir acceso a Docker desde el backend
    environment:
      - FLASK_ENV=development
    privileged: true  # Requerido para gestionar contenedores desde el backend
    networks:
      - lab_app_net

  frontend:
    build:
      context: ./labselector
    ports:
      - "3000:3000"  # Puerto para la aplicación Next.js
    volumes:
      - ./labselector:/frontend
    command: "npm run dev"  # Comando para iniciar Next.js en modo desarrollo
    working_dir: /frontend
    networks:
      - lab_app_net

  exercise_container:
    image: kalilinux/kali-rolling
    container_name: exercise_container
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    command: ["/bin/bash"]
    networks:
      - lab_app_net
