networks:
  lab_app_net:
    name: lab_app_net
    driver: bridge

services:
  webapp:
    build:
      context: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./dockerfiles:/app/dockerfiles
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
    privileged: true
    networks:
      - lab_app_net

  frontend:
    build:
      context: ./labselector
    ports:
      - "3000:3000"
    volumes:
      - ./labselector:/frontend
      - /frontend/node_modules
    command: "npm run dev"
    working_dir: /frontend
    networks:
      - lab_app_net

  exercise_container:
    image: kalilinux/kali-rolling
    container_name: exercise_container
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    command: ["/bin/bash"]
    networks:
      - lab_app_net
