version: "3.8"
networks:
  lab_app_net:
    driver: bridge
services:
  webapp:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "5001:5001"
    networks:
      - lab_app_net
    restart: always

  frontend:
    build:
      context: ./frontend/labselector
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    command: npm run start
    networks:
      - lab_app_net
    restart: always

  exercise_container:
    image: kalilinux/kali-rolling
    container_name: exercise_container
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    command: ["/bin/bash"]
    networks:
      - lab_app_net
    restart: always
