name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: your.registry.com/labcentral/backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: your.registry.com/labcentral/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_HOST: ${{ secrets.SERVER_HOST }}
      SSH_USER: ${{ secrets.SERVER_USER }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd /ruta/al/deploy
            docker-compose pull
            docker-compose up -d